[package]
name = "greeting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magnus = { git = "https://github.com/matsadler/magnus", branch = "main" }

[lib]
crate-type = ["cdylib"]
